name: 'BrowserStack'

on: [push, pull_request]

jobs:
  ubuntu-job:
    name: 'BrowserStack Test on Ubuntu'
    runs-on: ubuntu-latest
    steps:
      - name: 'BrowserStack Env Setup'
        uses: 'saraswati-padmawar/github-actions/setup-env@dependabot-bulk-updates'
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: BUILD_INFO

      - name: 'BrowserStackLocal Setup'
        uses: 'saraswati-padmawar/github-actions/setup-local@dependabot-bulk-updates'
        with:
          local-testing: start
          local-identifier: random
          local-logging-level: all-logs
    
      - name: 'Checkout Repository'
        uses: 'actions/checkout@v2'

      - name: 'Install Dependencies'
        run: npm install

      - name: 'Start HTTP Server'
        run: './node_modules/.bin/http-server -p 8099 &'

      - name: 'Run Tests'
        run: node index.js

      - name: 'Stop BrowserStackLocal'
        uses: 'saraswati-padmawar/github-actions/setup-local@dependabot-bulk-updates'
        with:
          local-testing: stop

  windows-job:
    name: 'BrowserStack Test on Windows'
    runs-on: windows-latest
    steps:
      - name: 'BrowserStack Env Setup'
        uses: 'saraswati-padmawar/github-actions/setup-env@dependabot-bulk-updates'
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: BUILD_INFO

      - name: 'BrowserStackLocal Setup'
        uses: 'saraswati-padmawar/github-actions/setup-local@dependabot-bulk-updates'
        with:
          local-testing: start
          local-identifier: random
          local-logging-level: all-logs
   
      - name: 'Checkout Repository'
        uses: 'actions/checkout@v2'

      - name: 'Install Dependencies'
        run: npm install

      - name: 'Start HTTP Server'
        run: './node_modules/.bin/http-server -p 8099 &'

      - name: 'Run Tests'
        run: node index.js

      - name: 'Stop BrowserStackLocal'
        uses: 'saraswati-padmawar/github-actions/setup-local@dependabot-bulk-updates'
        with:
          local-testing: stop
  
  macos-job:
    name: 'BrowserStack Test on macOS'
    runs-on: macos-latest
    steps:
      - name: 'BrowserStack Env Setup'
        uses: 'saraswati-padmawar/github-actions/setup-env@dependabot-bulk-updates'
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: BUILD_INFO

      - name: 'BrowserStackLocal Setup'
        uses: 'saraswati-padmawar/github-actions/setup-local@dependabot-bulk-updates'
        with:
          local-testing: start
          local-identifier: random
          local-logging-level: all-logs

      - name: 'Checkout Repository'
        uses: 'actions/checkout@v2'

      - name: 'Install Dependencies'
        run: npm install

      - name: 'Start HTTP Server'
        run: './node_modules/.bin/http-server -p 8099 &'

      - name: 'Run Tests'
        run: node index.js

      - name: 'Stop BrowserStackLocal'
        uses: 'saraswati-padmawar/github-actions/setup-local@dependabot-bulk-updates'
        with:
          local-testing: stop