name: 'BrowserStack'
on: [push, pull_request]

jobs:
  ubuntu-job:
    name: 'BrowserStack Test on Ubuntu'
    runs-on: ubuntu-latest
    steps:
      - name: 'BrowserStack Env Setup'
        uses: 'saraswati-padmawar/github-actions/setup-env@master'
        with:
          username:  ${{secrets.BROWSERSTACK_USERNAME}}
          access-key: ${{secrets.BROWSERSTACK_ACCESS_KEY}}
          build-name: BUILD_INFO